---

- name: mongodb reload
  become: yes
  service: name={{ mongodb_daemon_name }} state=reloaded
  when: mongodb_manage_service

- name: mongodb restart
  become: yes
  service: name={{ mongodb_daemon_name }} state=restarted
  when: mongodb_manage_service

- name: mongodb-mms-automation-agent restart
  become: yes
  service: name=mongodb-mms-automation-agent state=restarted
  when: mongodb_manage_service

- name: reload systemd
  become: yes
  shell: systemctl daemon-reload
  when: mongodb_is_systemd and mongodb_manage_service

- name: restart sysfsutils
  become: yes
  service: name=sysfsutils state=restarted
